# This is a basic workflow to help you get started with Actions

name: CC Frontend Pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DEPLOYMENT_NAME: cc-frontend
  TAG: latest

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
  
    # Name of Job
    name: Build Maven Project
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up JDK
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with: 
          java-version: '11'
          distribution: 'adopt'
      
      # Build Maven Project and skip Tests
      - name: Build with Maven
        run: mvn clean package -DskipTests        

      # List target directory after building jar
      - name: List target directory
        run: |
          ls -la
          cd target
          ls -la
        
      # Upload Target Directory as GitHub Artefact
      - name: Cache Target Directory
        uses: actions/upload-artifact@v3
        with:
          name: target-directory
          path: target
  
  # This is the second job of the workflow called "test"
  test:  
  
    name: Test Maven Project
    runs-on: ubuntu-latest
    needs: [build]

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Maven JUnit Tests
        run: mvn test

      - name: JUnit Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Maven Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true

      - name: Setup PMD Source Code Analyzer
        uses: sfdx-actions/setup-pmd@v1
    
      - name: Run PMD Source Code Analyzer
        run: pmd -d ./src -R pmd_ruleset.xml -f text
  
  # This is the third job of the workflow called "image"
  image: 
  
    name: Push Maven Project to DockerHub
    runs-on: ubuntu-latest
    needs: [test]

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Target Directory
        uses: actions/download-artifact@v3
        with:
          name: target-directory
          path: target
    
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: target

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}   

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DEPLOYMENT_NAME }}:${{ env.TAG }}
